This exception is not useful, but causes problems when mergen more than 2 reports
Exception while merging report
java.lang.IllegalArgumentException: Unit c8ey (c8ey) already exists
    at magellan.library.GameData.addOldUnit(GameData.java:539)
    at magellan.library.GameDataMerger.addOldUnits(GameDataMerger.java:901)
    at magellan.library.GameDataMerger.mergeIt(GameDataMerger.java:617)
    at magellan.library.GameDataMerger.merge(GameDataMerger.java:100)
    at magellan.library.utils.ReportMerger.mergeReport(ReportMerger.java:520)
    at magellan.library.utils.ReportMerger.mergeThread(ReportMerger.java:339)
    at magellan.library.utils.ReportMerger$1.run(ReportMerger.java:295)
    at java.base/java.lang.Thread.run(Thread.java:834)